{{- /* Copyright (c) 2026 Electronic Arts Inc. All rights reserved. */ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grpc-studio.frontendName" . }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grpc-studio.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  nginx.conf: |
{{ tpl (.Files.Get "application/nginx.conf.tpl") . | indent 4 }}
