# Copyright (c) 2026 Electronic Arts Inc. All rights reserved.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grpc-studio.frontendConfigName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grpc-studio.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  frontend.yaml: |
{{ tpl (.Files.Get "application/frontend.yaml.tpl") . | indent 4 }}
