# Copyright (c) 2026 Electronic Arts Inc. All rights reserved.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-studio.frontendServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grpc-studio.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "grpc-studio.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
