# Copyright (c) 2026 Electronic Arts Inc. All rights reserved.

connection:
  mode: insecure
  target:
    host: my-grpc-server.default.svc.cluster.local
    port: 50051

auth:
  defaultPlugin: none

ingress:
  enabled: false
